### ISSUE TITLE
Running hello world with error `InsufficientGas in command 0`

### ISSUE THREAD

**Issue by lidh15** [sui-foundation/sui-move-intro-course#29]
I was following the unit one class and published with default gas value 30000:
```
$ sui client publish --gas-budget 30000
```
but it said that:
```
Successfully verified dependencies on-chain against source.
Error executing transaction: Failure {
    error: "InsufficientGas in command 0",
}
```

**Comment by avcdsld** [comment]
I had the same error, but after I set gas-budget to a large value, it was fine.
`--gas-budget 20000000`

I think the documentation needs to be corrected.
