### ISSUE TITLE
Sui docker Image's platform supports arm based machine but its not native to intel machines.

### ISSUE THREAD

**Issue by JinwooSeong** [sui-foundation/sui-move-intro-course#3]
`docker run --entrypoint /bin/sh -itd hyd628/sui-move-intro-course:latest`
`WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested`

Suggest to make two different versions of docker image, seperated by tag, ex `:arm`, `:intel`  and upload a intel machine compiled image.

**Comment by hyd628** [comment]
Good catch. Looks like you can do on an ARM computer with an emulator: 

https://binx.io/2022/06/23/how-to-run-intel-docker-images-on-mac-m1-using-lima/

**Comment by llllllluc** [comment]
Hi @hyd628, i also run into this issue when I try to run the container. I'm using an intel mac, looks like the image only supports arm mac.

**Comment by hyd628** [comment]
Thanks @llllllluc . Added a note for starting with a base Ubuntu or Rust docker appropriate for your computer if the included image doesnt work.
