### ISSUE TITLE
We don't need to run docker if we install sui binary locally, right?

### ISSUE THREAD

**Issue by llllllluc** [sui-foundation/sui-move-intro-course#7]
Thanks for making this intro, I've been looking for sui tutorials that is concise like this one! 

In the [env setup](https://github.com/sui-foundation/sui-move-intro-course/blob/main/unit-one/lessons/1_set_up_environment.md), docker image is only for running sui binary without install it locally, right? Could you also link the docker compose file of the image?

**Comment by hyd628** [comment]
Hey @llllllluc , you don't need to use the Docker image if you install the binaries locally. Cheers.
