### ISSUE TITLE
RPC Error trying to publish the contract from unit one 

### ISSUE THREAD

**Issue by Skunkw0rks** [sui-foundation/sui-move-intro-course#76]
Following the steps from this [lesson](https://github.com/sui-foundation/sui-move-intro-course/blob/main/unit-one/lessons/5_contract_deployment.md) I am trying to deploy the contract however I am getting the following error message.

> RPC call failed: ErrorObject { code: ServerError(-32002), message: "Transaction execution failed due to issues with transaction inputs, please review the errors and try again: TransferObjects, MergeCoin, and Publish cannot have empty arguments. If MakeMoveVec has empty arguments, it must have a type specified.", data: None }
> 
> Caused by:
>     RPC call failed: ErrorObject { code: ServerError(-32002), message: "Transaction execution failed due to issues with transaction inputs, please review the errors and try again: TransferObjects, MergeCoin, and Publish cannot have empty arguments. If MakeMoveVec has empty arguments, it must have a type specified.", data: None }

Is there a missing step somewhere?

**Comment by kalbroni7** [comment]
When encountering the error message you provided, it's essential to review the specific contract code and transaction that triggered the issue. Here are some steps to consider:

1. **Function Arguments**: Verify that you're passing valid arguments to your contract functions. Ensure that none of the required fields are empty. The error message suggests that functions like `TransferObjects`, `MergeCoin`, and `Publish` cannot have empty arguments. If you're using `MakeMoveVec`, ensure it has a specified type if its arguments are empty.

2. **Contract Dependencies**: Check if your contract relies on other objects or functions. Ensure that these dependencies are correctly initialized and accessible during deployment.

3. **Transaction Order**: Confirm the order of your transactions. Some dependencies might require specific execution order. Ensure that any prerequisites are met before deploying the contract.

4. **Version Compatibility**: Ensure that the contract version matches the current version. Mismatched versions can lead to execution failures.

5. **Debugging Tools**: Use any available debugging tools or logs to identify the exact point of failure. Look for specific lines of code that trigger the error.

Remember that contract deployment involves various components, and pinpointing the issue may require a thorough examination. If you encounter further challenges or need additional assistance, feel free to share more details, and I'll be here to help! 😊🚀
